LOCALHOST = "127.0.0.1"
ENCODING = "utf-8"
REQUEST_METHODS = ["get", "delete", "head", "post"]
DIRECTORY_NODE_HOST = LOCALHOST
DIRECTORY_NODE_PORT = 5050
AUTHENTICATION_SERV_HOST = LOCALHOST
AUTHENTICATION_SERV_PORT = 5070
